# Generated by Django 2.2.4 on 2020-05-03 11:21

import autoslug.fields
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=300, null=True, verbose_name='SEO заголовок')),
                ('seo_description', models.TextField(blank=True, null=True, verbose_name='SEO описание')),
                ('seo_keywords', models.CharField(blank=True, max_length=300, null=True, verbose_name='SEO ключевые слова')),
                ('category_title', models.CharField(max_length=130, verbose_name='Заголовок категории')),
                ('category_description', models.TextField(blank=True, help_text='Если понадобиться вывести текст в категории для SEO', null=True, verbose_name='Описание категории')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='category_title', unique_with=['id', 'created_date__day'])),
                ('is_active', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=300, null=True, verbose_name='SEO заголовок')),
                ('seo_description', models.TextField(blank=True, null=True, verbose_name='SEO описание')),
                ('seo_keywords', models.CharField(blank=True, max_length=300, null=True, verbose_name='SEO ключевые слова')),
                ('post_title', models.CharField(max_length=180, verbose_name='Заголовок статьи')),
                ('post_body', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст статьи')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='post_title', unique_with=['id', 'pub_date__day'])),
                ('preview_image', models.ImageField(blank=True, default=None, null=True, upload_to='uploads/blog_previews/', verbose_name='Превью статьи')),
                ('is_active', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='Дата публикации')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('post_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_posts', to='blog.Category')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=60, verbose_name='Автор комментария')),
                ('author_email', models.EmailField(max_length=254, verbose_name='E-mail автора комментария')),
                ('comment_body', models.TextField(max_length=250, verbose_name='Текст комментария')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='blog.Posts', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-pub_date'],
            },
        ),
    ]
