# Generated by Django 2.2.4 on 2020-09-12 14:19

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='slug',
            field=autoslug.fields.AutoSlugField(auto_created=True, editable=True, populate_from='post_title', unique_with=['id', 'pub_date__day']),
        ),
    ]
