# Generated by Django 2.2.4 on 2020-09-12 14:20

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200912_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=True, populate_from='post_title', unique_with=['id', 'pub_date__day']),
        ),
    ]
