# Generated by Django 2.2.4 on 2020-05-03 11:13

import autoslug.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=300, null=True, verbose_name='SEO заголовок')),
                ('seo_description', models.TextField(blank=True, null=True, verbose_name='SEO описание')),
                ('seo_keywords', models.CharField(blank=True, max_length=300, null=True, verbose_name='SEO ключевые слова')),
                ('title', models.CharField(help_text='Введите название проекта галерии', max_length=200, verbose_name='Название проекта')),
                ('project_description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание проекта')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', verbose_name='url-проекта')),
                ('preview', models.ImageField(default='default_project.jpg', upload_to='uploads/gallery/', verbose_name='Изображение на превью')),
                ('comp_view', models.ImageField(default='comp_view.jpg', upload_to='uploads/gallery/comp_view/', verbose_name='Изображение-результат')),
                ('technologies', models.CharField(blank=True, max_length=220, null=True, verbose_name='Использованные технологии')),
                ('project_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на проект')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='Дата публикации')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галерея',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Site Name', max_length=255)),
                ('favicon', models.FileField(default='favicon.ico', upload_to='favicon/', verbose_name='Favicon для сайта')),
                ('avatar', models.ImageField(blank=True, upload_to='avatar/', verbose_name='Аватар сайта (личное изображение)')),
                ('my_cv', models.FileField(upload_to='files/cv/', verbose_name='Файл резюме')),
                ('email', models.EmailField(max_length=254, verbose_name='Мой e-mail')),
                ('about', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True, verbose_name='Блок обо мне на главной')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
