# Generated by Django 2.2.4 on 2020-05-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='linkedin',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на LinkIdn'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='skype',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Ссылка на Skype'),
        ),
    ]
