# Generated by Django 2.2.4 on 2020-05-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcard', '0005_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='city',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Текущий город'),
        ),
    ]
