# Generated by Django 2.2.4 on 2020-08-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcard', '0006_siteconfig_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='linkedin',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на LinkEdin'),
        ),
    ]
