# Generated by Django 2.2.4 on 2020-08-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcard', '0007_auto_20200830_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='footer_scripts',
            field=models.TextField(blank=True, verbose_name='Скрипты в подвале сайта'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='header_scripts',
            field=models.TextField(blank=True, verbose_name='Скрипты в шапке сайта'),
        ),
    ]
