# Generated by Django 2.2.4 on 2020-08-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcard', '0008_auto_20200830_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='my_cv',
            field=models.FileField(blank=True, null=True, upload_to='files/cv/', verbose_name='Файл резюме'),
        ),
    ]
