# Generated by Django 2.2.4 on 2020-09-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcard', '0009_auto_20200830_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='is_services_active',
            field=models.BooleanField(default=True, verbose_name='Включить блок Мои услуги на главной'),
        ),
    ]
