# Generated by Django 2.2.4 on 2020-09-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcard', '0011_siteconfig_is_portfolio_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skills',
            options={'ordering': ['order_index'], 'verbose_name': 'Навык', 'verbose_name_plural': 'Навыки'},
        ),
        migrations.AddField(
            model_name='skills',
            name='order_index',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
