# Generated by Django 2.2.4 on 2020-05-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSeo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_seo_title', models.CharField(max_length=220, verbose_name='SEO заголовок главной страницы')),
                ('main_seo_description', models.CharField(max_length=220, verbose_name='SEO описание главной страницы')),
                ('main_seo_keywords', models.CharField(max_length=220, verbose_name='SEO ключевые слова главной страницы')),
                ('blog_seo_title', models.CharField(max_length=220, verbose_name='SEO заголовок для блога')),
                ('blog_seo_description', models.CharField(max_length=220, verbose_name='SEO описание для блога')),
                ('blog_seo_keywords', models.CharField(max_length=220, verbose_name='SEO ключевые слова для блога')),
                ('portfolio_seo_title', models.CharField(max_length=220, verbose_name='SEO заголовок для блога')),
                ('portfolio_description', models.CharField(max_length=220, verbose_name='SEO описание для блога')),
                ('portfolio_seo_keywords', models.CharField(max_length=220, verbose_name='SEO ключевые слова для блога')),
            ],
            options={
                'verbose_name': 'SEO настройки сайта',
                'verbose_name_plural': 'SEO настройки сайта',
            },
        ),
    ]
