# Generated by Django 2.2.4 on 2020-08-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotsHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(help_text='Будет указано в robots.txt как главное зеркало сайта в директиве Host. Например - (HOST: alexlinus.ru)', max_length=200, verbose_name='Главное зеркало')),
            ],
            options={
                'verbose_name': 'Robots.txt - Главное зеркало',
                'verbose_name_plural': 'Robots.txt - Главное зеркало',
            },
        ),
        migrations.CreateModel(
            name='RobotsUrlPattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_pattern', models.CharField(help_text="Внимание: учитывается регистр!Если в конце пропущен слэш, то под шаблон попадут все файлы, путь к которым начинается с таких же символов. Например: под шаблон «/admin' так же попадет «/admin.html».Часть поисковых систем понимают звездочку (*) как произвольное количество любых символов и знак доллара ($) как символ конца URL. Например: «/*.jpg$»", max_length=300, verbose_name='Шаблон url')),
            ],
            options={
                'verbose_name': 'Robots.txt - URL-паттерн',
                'verbose_name_plural': 'Robots.txt - URL-паттерн',
            },
        ),
        migrations.CreateModel(
            name='RobotsTxt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robot', models.CharField(help_text='Название робота (User agent). Введите звездочку (*) для применения правил ко всем роботов. Полный список можно посмотреть в базе данных веб-ботов.', max_length=200, verbose_name='Название робота')),
                ('is_active', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('allowed_urls', models.ManyToManyField(blank=True, help_text='URL адреса разрешенные для индексации поисковыми роботами.', related_name='allowed_urls', to='seo.RobotsUrlPattern', verbose_name='Разрешенные url')),
                ('disallowed_urls', models.ManyToManyField(blank=True, related_name='disallowed_urls', to='seo.RobotsUrlPattern', verbose_name='Запрещенные url')),
            ],
            options={
                'verbose_name': 'Robots.txt - Правила индексации',
                'verbose_name_plural': 'Robots.txt - Правила индексации',
            },
        ),
    ]
