# Generated by Django 2.2.4 on 2020-09-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0002_robotshost_robotstxt_robotsurlpattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalseo',
            name='contact_seo_description',
            field=models.CharField(default='', max_length=220, verbose_name='SEO описание для блога'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='globalseo',
            name='contact_seo_keywords',
            field=models.CharField(default='', max_length=220, verbose_name='SEO ключевые слова для блога'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='globalseo',
            name='contact_seo_title',
            field=models.CharField(default='', max_length=220, verbose_name='SEO заголовок для блога'),
            preserve_default=False,
        ),
    ]
